import mongoose from "mongoose";
import FoodItem from "../models/FoodItem.js";
import dotenv from "dotenv";

dotenv.config();

const seedFoods = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    await FoodItem.deleteMany();

    const foods = [
      // Hero Trending Items (5 items)
      { name: "Classic Margherita Pizza", image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002", customImage: "/foodimage/pizza.webp", customImage1: "/foodimage/pizza1.webp", description: "Freshly baked pizza with rich tomato sauce, mozzarella cheese, and basil leaves.", price: 299, category: "Italian", rating: 4.7, spicyLevel: 1, ingredients: ["Flour", "Tomato", "Mozzarella", "Basil"], isTrending: true, tagline: "Cheesy Bliss in Every Slice! 🍕🔥", tags: ["trending", "cheesy", "best-seller"], nutritionInfo: "Calories: 280 kcal", spoonacularId: 1001 },
      { name: "Chicken Dum Biryani", image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0", customImage: "/foodimage/biriyani.webp", customImage1: "/foodimage/biriyani1.webp", description: "Aromatic basmati rice cooked with tender chicken and royal spices.", price: 349, category: "Indian", rating: 4.8, spicyLevel: 4, ingredients: ["Basmati Rice", "Chicken", "Spices", "Ghee"], isTrending: true, tagline: "Royal Feast for the Soul! 👑✨", tags: ["most-loved", "spicy", "royal"], nutritionInfo: "Calories: 420 kcal", spoonacularId: 1002 },
      { name: "Japanese Sushi Platter", image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c", customImage: "/foodimage/sushi.webp", customImage1: "/foodimage/sushi1.webp", description: "Freshly prepared sushi rolls with premium seafood and rice.", price: 499, category: "Japanese", rating: 4.6, spicyLevel: 0, ingredients: ["Rice", "Seafood", "Seaweed"], isTrending: true, tagline: "Ocean Fresh, Precision Crafted! 🍣🌊", tags: ["fresh", "light", "popular"], nutritionInfo: "Calories: 250 kcal", spoonacularId: 1003 },
      { name: "Loaded Cheese Burger", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd", customImage: "/foodimage/burger.webp", customImage1:"/foodimage/burger1.webp" , description:"Juicy grilled burger with double cheese and crunchy veggies.", price : 259 , category : 'American' , rating : 4.5 , spicyLevel : 2 , ingredients : ['Bun','Beef Patty','Cheese','Lettuce'], isTrending:true , tagline:"Juicy, Cheesy, Exploding with Flavor! 🍔💥" , tags:["juicy","comfort-food","classic"] , nutritionInfo:"Calories : 520 kcal" , spoonacularId : 1004 },
      { name:"Creamy Alfredo Pasta" , image:"https://images.unsplash.com/photo-1645112411341-6c4fd0237b69" , customImage:"/foodimage/pasta.webp" , customImage1:"/foodimage/pasta1.webp" , description:"Silky creamy pasta tossed with garlic, herbs, and parmesan." , price : 289 , category : 'Italian' , rating : 4.4 , spicyLevel : 1 , ingredients : ['Pasta','Cream','Garlic','Cheese'] , isTrending:true , tagline:"Creamy Comfort in a Bowl! 🍝🧀" , tags:["comfort","creamy","popular"] , nutritionInfo:"Calories : 350 kcal" , spoonacularId : 1005 },
      // Additional Trending Items (3 items to make 8)
      { name: "Paneer Tikka", image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0", customImage: "/foodimage/paneertikka.webp", description: "Spiced grilled cottage cheese cubes with veggies.", price: 280, category: "Indian", rating: 4.7, spicyLevel: 3, ingredients: ["Paneer", "Yogurt", "Lemon Juice", "Ginger Garlic Paste", "Tikka Masala Spices", "Bell Peppers"], isTrending: true, tagline: "Smoky, Spicy, and Perfectly Grilled! 🧀🔥", tags: ["grilled", "spicy", "vegetarian"], nutritionInfo: "Calories: 290 kcal", spoonacularId: 2006 },
      { name: "Chocolate Lava Cake", image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c", customImage: "/foodimage/chocolatelavacake.webp", description: "Warm chocolate cake with a molten gooey center.", price: 220, category: "Dessert", rating: 4.9, spicyLevel: 0, ingredients: ["Dark Chocolate", "Butter", "Eggs", "Sugar", "Flour"], isTrending: true, tagline: "Molten Chocolate Heaven! 🍫🌋", tags: ["sweet", "gooey", "indulgent"], nutritionInfo: "Calories: 380 kcal", spoonacularId: 2004 },
      { name: "Chicken Shawarma", image: "https://images.unsplash.com/photo-1633321769045-20971dc9f3b6", customImage: "/foodimage/shawarma.webp", description: "Marinated chicken roasted slowly and wrapped in pita bread with garlic sauce and pickles.", price: 180, category: "Arabian", rating: 4.7, spicyLevel: 2, ingredients: ["Chicken", "Pita Bread", "Garlic Sauce (Toum)", "Pickles", "Fries"], isTrending: true, tagline: "The Authentic Arabian Delight! 🌯🥙", tags: ["savory", "wrap", "middle-eastern"], nutritionInfo: "Calories: 320 kcal", spoonacularId: 2005 },

      // Other Foods (Non-Trending)
      { name: "Pasta Carbonara", image: "https://images.unsplash.com/photo-1612874742237-6526221588e3", customImage: "/foodimage/pastacarbonara.webp", description: "Creamy sauce with bacon, egg, and parmesan cheese.", price: 320, category: "Italian", rating: 4.7, spicyLevel: 1, ingredients: ["Spaghetti", "Eggs", "Pecorino Romano", "Guanciale", "Black Pepper"] },
      { name: "Lasagna", image: "https://images.unsplash.com/photo-1574868291534-18430db33f92", customImage: "/foodimage/lasagna.webp", description: "Layers of pasta, rich meat sauce, and melted cheese.", price: 350, category: "Italian", rating: 4.8, spicyLevel: 2, ingredients: ["Lasagna Sheets", "Ground Beef", "Tomato Sauce", "Mozzarella", "Ricotta", "Parmesan"] },
      { name: "Mushroom Risotto", image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371", customImage: "/foodimage/mushroom.webp", description: "Creamy rice dish cooked with wild mushrooms and herbs.", price: 300, category: "Italian", rating: 4.4, spicyLevel: 1, ingredients: ["Arborio Rice", "Mushrooms", "Vegetable Broth", "Parmesan Cheese", "White Wine", "Butter"] },
      { name: "Bruschetta", image: "https://images.unsplash.com/photo-1572695157369-a0eac271ad61", customImage: "/foodimage/bruschetta.webp", description: "Grilled bread topped with fresh tomatoes, garlic, and basil.", price: 180, category: "Italian", rating: 4.3, spicyLevel: 1, ingredients: ["Baguette", "Tomatoes", "Garlic", "Basil", "Olive Oil", "Balsamic Glaze"] },
      { name: "Fettuccine Alfredo", image: "https://images.unsplash.com/photo-1645112411341-6c4fd0237b69", customImage: "/foodimage/fettuccinealfredo.webp", description: "Rich creamy parmesan sauce served over fettuccine pasta.", price: 290, category: "Italian", rating: 4.6, spicyLevel: 1, ingredients: ["Fettuccine Pasta", "Heavy Cream", "Butter", "Parmesan Cheese", "Garlic"] },
      { name: "Garlic Bread", image: "https://images.unsplash.com/photo-1573140247632-f84660f67627", customImage: "/foodimage/garlicbread.webp", description: "Toasted bread topped with garlic, butter, and herbs.", price: 120, category: "Italian", rating: 4.5, spicyLevel: 1, ingredients: ["Baguette", "Butter", "Garlic", "Parsley", "Parmesan Cheese"] },

      // Indian
      { name: "Butter Chicken", image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398", customImage: "/foodimage/butterchicken.webp", description: "Tender chicken cooked in a rich tomato and butter gravy.", price: 380, category: "Indian", rating: 4.9, spicyLevel: 2, ingredients: ["Chicken", "Tomato Puree", "Butter", "Cream", "Cashews", "Garam Masala", "Fenugreek"] },
      { name: "Masala Dosa", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc", customImage: "/foodimage/masaladosa.webp", description: "Crispy rice crepe filled with spiced potato masala.", price: 150, category: "Indian", rating: 4.6, spicyLevel: 2, ingredients: ["Rice Batter", "Urad Dal", "Potatoes", "Onions", "Mustard Seeds", "Curry Leaves", "Turmeric"] },
      { name: "Rogan Josh", image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641", customImage:"/foodimage/rogan.webp" , description:"Aromatic lamb curry from Kashmir with traditional spices.", price : 420 , category : "Indian" , rating : 4.7 , spicyLevel : 3, ingredients: ["Lamb", "Yogurt", "Kashmiri Chili Powder", "Fennel Seeds", "Ginger Powder", "Mustard Oil"] },
      { name : "Dal Makhani" , image : "https://images.unsplash.com/photo-1546833999-b9f581a1996d" , customImage : "/foodimage/makhani.webp" , description : "Creamy black lentils cooked overnight with butter and cream." , price : 220 , category : "Indian" , rating : 4.5 , spicyLevel : 1, ingredients: ["Black Lentils", "Kidney Beans", "Butter", "Cream", "Tomato Puree", "Ginger", "Garlic"] },
      { name: "Idli", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc", customImage: "/foodimage/idli.webp", description: "Soft and fluffy steamed rice cakes served with chutney and sambar.", price: 80, category: "Indian", rating: 4.5, spicyLevel: 1, ingredients: ["Rice", "Urad Dal", "Fenugreek Seeds", "Salt"] },
      { name: "Medu Vada", image: "https://images.unsplash.com/photo-1630383249896-424e482df921", customImage: "/foodimage/vada.webp", description: "Crispy deep-fried savory donuts made from lentil batter.", price: 90, category: "Indian", rating: 4.4, spicyLevel: 2, ingredients: ["Urad Dal", "Green Chilies", "Ginger", "Curry Leaves", "Black Pepper", "Onions"] },
      { name: "Kathi Roll", image: "https://images.unsplash.com/photo-1606491956689-2ea28c674675", customImage: "/foodimage/kathiroll.webp", description: "Skewer-roasted kebab wrapped in a paratha bread.", price: 150, category: "Indian", rating: 4.6, spicyLevel: 3, ingredients: ["Paratha", "Chicken/Paneer", "Onions", "Bell Peppers", "Green Chutney", "Chaat Masala"] },
      { name: "Pani Puri", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950", customImage: "/foodimage/panipuri.webp", description: "Hollow crispy shells filled with spiced water and potatoes.", price: 60, category: "Indian", rating: 4.8, spicyLevel: 3, ingredients: ["Semolina Puris", "Potatoes", "Chickpeas", "Tamarind Water", "Mint Water", "Chaat Masala"] },
      { name: "Vada Pav", image: "https://images.unsplash.com/photo-1603064752734-4c48eff53d05", customImage: "/foodimage/vadapav.webp", description: "The Indian burger - deep fried potato dumpling inside a bread bun.", price: 50, category: "Indian", rating: 4.7, spicyLevel: 3, ingredients: ["Potato Fritter", "Bread Bun", "Garlic Chutney", "Green Chutney", "Fried Green Chili"] },
      { name: "Pav Bhaji", image: "https://images.unsplash.com/photo-1606491956689-2ea28c674675", customImage: "/foodimage/pavpaji.webp", description: "Spicy vegetable mash served with soft buttered bread rolls.", price: 140, category: "Indian", rating: 4.7, spicyLevel: 3, ingredients: ["Mixed Vegetables", "Butter", "Pav Bhaji Masala", "Bread Rolls", "Onions"] },
      { name: "Ven Pongal", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc", customImage: "/foodimage/pongal.webp", description: "Comforting rice and lentil dish seasoned with black pepper and cumin.", price: 100, category: "Indian", rating: 4.5, spicyLevel: 1, ingredients: ["Rice", "Moong Dal", "Black Pepper", "Cumin", "Ginger", "Curry Leaves", "Ghee", "Cashews"] },
      { name: "Samosa", image: "https://images.unsplash.com/photo-1601050690597-df0568f70950", customImage: "/foodimage/samosa.webp", description: "Fried pastry with a savory filling of spiced potatoes and peas.", price: 40, category: "Indian", rating: 4.6, spicyLevel: 2, ingredients: ["All Purpose Flour", "Potatoes", "Peas", "Cumin", "Coriander Seeds", "Garam Masala", "Green Chilies"] },
      { name: "Uttapam", image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc", customImage: "/foodimage/uttapam.webp", description: "Thick pancake made from fermented rice and lentil batter topped with veggies.", price: 110, category: "Indian", rating: 4.4, spicyLevel: 2, ingredients: ["Rice Batter", "Urad Dal", "Onions", "Tomatoes", "Green Chilies", "Coriander"] },

      // Chinese
      { name: "Kung Pao Chicken", image: "https://images.unsplash.com/photo-1525755662778-989d0524087e", customImage: "/foodimage/kungpo.webp", description: "Spicy stir-fry dish made with chicken, peanuts, and vegetables.", price: 320, category: "Chinese", rating: 4.6, spicyLevel: 3, ingredients: ["Chicken", "Peanuts", "Dried Red Chilies", "Scallions", "Soy Sauce", "Vinegar", "Ginger"] },
      { name: "Dim Sum Platter", image: "https://images.unsplash.com/photo-1563245372-f21720e32c4d", customImage: "/foodimage/dumplings.webp", description: "Assorted steamed dumplings with various fillings.", price: 350, category: "Chinese", rating: 4.7, spicyLevel: 1, ingredients: ["Flour Wrappers", "Minced Chicken/Prawns/Vegetables", "Soy Sauce", "Sesame Oil", "Ginger"] },
      { name: "Hakka Noodles", image: "https://images.unsplash.com/photo-1585032226651-759b368d7246", customImage: "/foodimage/hakkanoodles.webp", description: "Stir-fried noodles with crunchy vegetables and soy sauce.", price: 200, category: "Chinese", rating: 4.4, spicyLevel: 2, ingredients: ["Noodles", "Cabbage", "Carrots", "Bell Peppers", "Soy Sauce", "Vinegar", "Garlic"] },
      { name: "Spring Rolls", image: "https://images.unsplash.com/photo-1544025162-d76690b67f61", customImage:"/foodimage/springroll.webp" , description:"Crispy golden rolls filled with shredded vegetables.", price : 180 , category : "Chinese" , rating : 4.5 , spicyLevel : 1, ingredients: ["Spring Roll Wrappers", "Cabbage", "Carrots", "Bean Sprouts", "Soy Sauce", "Garlic"] },
      { name : "Schezwan Fried Rice" , image : "https://images.unsplash.com/photo-1603133872878-684f208fb74b" , customImage : "/foodimage/schezwanrice.webp" , description : "Spicy fried rice tossed with schezwan sauce and veggies." , price : 240 , category : "Chinese" , rating : 4.6 , spicyLevel : 3, ingredients: ["Rice", "Mixed Vegetables", "Schezwan Sauce", "Soy Sauce", "Spring Onions", "Garlic"] },
      { name : "Manchurian" , image : "https://images.unsplash.com/photo-1567510615292-477a31467d6b" , customImage:"/foodimage/manchurian.webp" , description:"Vegetable balls tossed in a spicy, sweet and tangy sauce." , price : 220 , category :"Chinese" , rating : 4.5 , spicyLevel : 2, ingredients: ["Cabbage", "Carrots", "Corn Flour", "Soy Sauce", "Ginger", "Garlic", "Spring Onions"] },

      // American
      { name: "Classic Cheeseburger", image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd", customImage: "/foodimage/clasicburger.webp", description: "Juicy beef patty topped with cheddar, lettuce, and tomato.", price: 280, category: "American", rating: 4.7, spicyLevel: 1, ingredients: ["Beef Patty", "Burger Bun", "Cheddar Cheese", "Lettuce", "Tomato", "Pickles", "Mayonnaise"] },
      { name: "BBQ Ribs", image: "https://images.unsplash.com/photo-1544025162-d76690b67f61", customImage: "/foodimage/bbq.webp", description: "Tender pork ribs glazed with smoky BBQ sauce.", price: 450, category: "American", rating: 4.8, spicyLevel: 2, ingredients: ["Pork Ribs", "BBQ Sauce", "Brown Sugar", "Paprika", "Garlic Powder", "Cayenne Pepper"] },
      { name: "Mac and Cheese", image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6", customImage: "/foodimage/macandcheese.webp", description: "Classic comfort food with rich cheesy pasta.", price: 250, category: "American", rating: 4.5, spicyLevel: 0, ingredients: ["Macaroni Pasta", "Cheddar Cheese", "Milk", "Butter", "Flour", "Breadcrumbs"] },
      { name: "Hot Dog", image: "https://images.unsplash.com/photo-1612392062631-94dd858cba88", customImage:"/foodimage/hotdog.webp" , description:"Grilled sausage in a bun with mustard and ketchup.", price : 150 , category : "American" , rating : 4.2 , spicyLevel : 1, ingredients: ["Sausage", "Hot Dog Bun", "Mustard", "Ketchup", "Onions"] },
      { name: "Buffalo Wings", image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f", customImage:"/foodimage/buffalowings.webp" , description:"Spicy chicken wings served with ranch dip.", price : 300 , category : "American" , rating : 4.6 , spicyLevel : 3, ingredients: ["Chicken Wings", "Hot Sauce", "Butter", "Vinegar", "Garlic Powder"] },
      { name: "Grilled Sandwich", image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af", customImage:"/foodimage/sandwich.webp" , description:"Perfectly toasted bread with melted cheese and fillings.", price : 180 , category : "American" , rating : 4.3 , spicyLevel : 1, ingredients: ["Bread Slices", "Cheese Slices", "Butter", "Tomatoes", "Cucumber", "Lettuce"] },
      { name: "Grilled Chicken", image: "https://images.unsplash.com/photo-1532550907401-a500c9a57435", customImage: "/foodimage/grilkledchicken.webp", description: "Juicy chicken breast grilled to perfection with herbs.", price: 350, category: "American", rating: 4.6, spicyLevel: 2, ingredients: ["Chicken Breast", "Olive Oil", "Lemon Juice", "Garlic", "Herbs (Rosemary, Thyme)", "Black Pepper"] },

      // Dessert
      { name: "New York Cheesecake", image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50", customImage: "/foodimage/cheesecake.webp", description: "Classic creamy cheesecake with a graham cracker crust.", price: 250, category: "Dessert", rating: 4.8, spicyLevel: 0, ingredients: ["Cream Cheese", "Sugar", "Eggs", "Graham Cracker Crust", "Sour Cream", "Vanilla Extract"] },
      { name: "Ice Cream Sundae", image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb", customImage: "/foodimage/icecreamsundae.webp", description: "Scoops of vanilla ice cream topped with syrup and nuts.", price: 180, category: "Dessert", rating: 4.6, spicyLevel: 0, ingredients: ["Vanilla Ice Cream", "Chocolate Syrup", "Nuts", "Whipped Cream", "Cherry"] },
      { name: "Brownie with Ice Cream", image: "https://images.unsplash.com/photo-1564355808539-22fda35bed7e", customImage: "/foodimage/fudgy.webp", description: "Fudgy chocolate brownie served with vanilla ice cream.", price: 200, category: "Dessert", rating: 4.7, spicyLevel: 0, ingredients: ["Chocolate", "Butter", "Sugar", "Flour", "Eggs", "Cocoa Powder", "Vanilla Ice Cream"] },
      { name: "Fruit Tart", image: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13", customImage:"/foodimage/fruittart.webp" , description:"Crispy pastry shell filled with custard and fresh fruits.", price : 220 , category : "Dessert" , rating : 4.5 , spicyLevel : 0, ingredients: ["Tart Shell", "Pastry Cream", "Strawberries", "Kiwis", "Blueberries", "Glaze"] },
      { name:"Waffles" , image:"https://images.unsplash.com/photo-1562376552-0d160a2f238d" , customImage:"/foodimage/waffles.webp" , description:"Crispy golden waffles served with maple syrup and berries." , price : 190 , category : "Dessert" , rating : 4.6 , spicyLevel : 0, ingredients: ["Flour", "Eggs", "Milk", "Butter", "Baking Powder", "Maple Syrup"] },
      { name: "Gulab Jamun", image: "https://images.unsplash.com/photo-1589119908995-c6837fa14848", customImage: "/foodimage/gulab.webp", description: "Soft berry-sized balls made with milk solids soaked in rose flavored sugar syrup.", price: 80, category: "Dessert", rating: 4.8, spicyLevel: 0, ingredients: ["Milk Powder", "Maida", "Ghee", "Milk", "Sugar", "Cardamom", "Rose Water"] },

      // Arabian
      { name: "Falafel Wrap", image: "https://images.unsplash.com/photo-1593001874117-c99c800e3eb7", customImage:"/foodimage/falafel.webp" , description:"Crispy fried balls of ground chickpeas served in a wrap with tahini and fresh veggies.", price : 150 , category : "Arabian" , rating : 4.5 , spicyLevel : 1, ingredients: ["Chickpeas", "Parsley", "Garlic", "Cumin", "Pita Bread", "Tahini Sauce", "Tomatoes"] },
      { name: "Mutton Mandi", image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0", customImage:"/foodimage/muttonmandi.webp" , description:"Traditional Yemeni dish consisting of tender meat and rice cooked with a special blend of spices in a tandoor.", price : 450 , category : "Arabian" , rating : 4.8 , spicyLevel : 2, ingredients: ["Mutton", "Basmati Rice", "Mandi Spice Mix", "Dried Lemon", "Saffron", "Charcoal Smoke"] },
      { name: "Hummus with Pita", image: "https://images.unsplash.com/photo-1577906096429-f736f9f3b212", customImage:"/foodimage/hummus.webp" , description:"Creamy dip made from chickpeas, tahini, lemon, and garlic, served with warm pita bread.", price : 160 , category : "Arabian" , rating : 4.6 , spicyLevel : 0, ingredients: ["Chickpeas", "Tahini", "Lemon Juice", "Garlic", "Olive Oil", "Pita Bread"] },
      { name: "Shish Tawook", image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1", customImage:"/foodimage/pannertikka.webp" , description:"Skewered chicken cubes marinated in yogurt, lemon, and garlic, grilled to perfection.", price : 320 , category :"Arabian" , rating : 4.7 , spicyLevel : 2, ingredients: ["Chicken Cubes", "Yogurt", "Lemon", "Garlic", "Tomato Paste", "Paprika", "Skewers"] },
      { name: "Kunafa", image: "https://images.unsplash.com/photo-1576506295286-5cda18df43e7", customImage:"/foodimage/kunafa.webp" , description:"Sweet Middle Eastern pastry made with spun pastry soaked in syrup and layered with cheese or cream.", price : 250 , category :"Arabian" , rating : 4.9 , spicyLevel : 0, ingredients: ["Kataifi Dough", "Cheese/Cream", "Sugar Syrup", "Pistachios", "Rose Water"] }
    ];

    await FoodItem.insertMany(foods);

    console.log("Foods seeded successfully");
    process.exit();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
};


seedFoods();